x-environment: &py-environment
  DOCKER_HOST: ${DOCKER_HOST:-missing}
  WS_PORT: ${WS_PORT:-6700}
  APISIX_PORT: ${APISIX_PORT:-6701}
  APISIX_SESSION_SECRET_KEY: ${APISIX_SESSION_SECRET_KEY:-supersecret123456789asdfasdfasdf}
  POSTGRES_PORT: ${POSTGRES_PORT:-6704}
  POSTGRES_USER: ${POSTGRES_USER:-postgres}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
  POSTGRES_DB: ${POSTGRES_DB:-keycloak}
  KEYCLOAK_PORT: ${KEYCLOAK_PORT:-6702}
  KEYCLOAK_SSL_PORT: ${KEYCLOAK_SSL_PORT:-6703}
  KEYCLOAK_REALM: ${KEYCLOAK_REALM:-ol-local}
  KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID:-apisix}
  KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET:-secret}
  KEYCLOAK_DISCOVERY_URL: ${KEYCLOAK_DISCOVERY_URL:-https://kc.odl.local:6703/realms/ol-local/.well-known/openid-configuration}
  KEYCLOAK_SVC_ADMIN: ${KEYCLOAK_SVC_ADMIN:-admin}
  KEYCLOAK_SVC_ADMIN_PASSWORD: ${KEYCLOAK_SVC_ADMIN_PASSWORD:-admin}
  KEYCLOAK_SVC_KEYSTORE_PASSWORD: ${KEYCLOAK_SVC_KEYSTORE_PASSWORD:-admin}
  KC_BOOTSTRAP_ADMIN_USERNAME: admin
  KC_BOOTSTRAP_ADMIN_PASSWORD: admin
  UE_LOGOUT_URL: ${UE_LOGOUT_URL:-http://ue.odl.local:7766/auth/logout/}

services:
  db:
    image: postgres:17
    ports:
      - "${POSTGRES_PORT}:5432"
    environment:
      <<: *py-environment
    env_file: .env
    volumes:
      - db:/var/lib/postgresql/data

  nginx:
    image: nginx:1.27
    ports:
      - "${NGINX_PORT}:80"
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/conf.d/web.conf
      - ./http:/usr/share/nginx/html

  web:
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      <<: *py-environment
    env_file: .env
    stdin_open: true
    tty: true
    ports:
      - ${WS_PORT}:7766
    volumes:
      - .:/src

  api:
    image: apache/apisix:latest
    environment:
      <<: *py-environment
    env_file: .env
    ports:
      - ${APISIX_PORT}:9080
    volumes:
      - ./config/apisix/config.yaml:/usr/local/apisix/conf/config.yaml
      - ./config/apisix/apisix.yaml:/usr/local/apisix/conf/apisix.yaml
      - ./config/apisix/debug.yaml:/usr/local/apisix/conf/debug.yaml

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      <<: *py-environment
    env_file: .env
    depends_on:
      - db
    ports:
      - ${KEYCLOAK_PORT}:${KEYCLOAK_PORT}
      - ${KEYCLOAK_SSL_PORT}:${KEYCLOAK_SSL_PORT}
    networks:
      default:
        aliases:
          - ${KEYCLOAK_SVC_HOSTNAME:-kc.odl.local}
    links:
      - db:uedb
    command: start --verbose --features scripts --import-realm --hostname=${KEYCLOAK_SVC_HOSTNAME:-kc.odl.local} --hostname-strict=false --hostname-debug=true --https-port=${KEYCLOAK_SSL_PORT} --https-certificate-file=/etc/x509/https/tls.crt --https-certificate-key-file=/etc/x509/https/tls.key --http-enabled=true --http-port=${KEYCLOAK_PORT} --config-keystore=/etc/keycloak-store --config-keystore-password=${KEYCLOAK_SVC_KEYSTORE_PASSWORD} --db=postgres --db-url-database=keycloak --db-url-host=db --db-schema=public --db-password=${POSTGRES_PASSWORD:-postgres} --db-username=postgres
    volumes:
      - keycloak-store:/etc/keycloak-store
      - ./config/keycloak/tls:/etc/x509/https
      - ./config/keycloak/realms:/opt/keycloak/data/import

volumes:
  keycloak-store:
  db: