upstreams:
  - id: 1
    nodes:
      "web:7766": 1
    type: roundrobin
  - id: 2
    nodes:
      "nginx:80": 1
    type: roundrobin

routes:
  - id: 1
    name: "http-stuff"
    desc: "HTTP stuff"
    priority: 2
    upstream_id: 2
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{UE_LOGOUT_URL}}
        set_userinfo_header: true
    uri: "/*"
  - id: 2
    name: "websocket-auth"
    desc: "WebSocket route"
    priority: 1
    upstream_id: 1
    plugins:
      openid-connect:
        client_id: ${{KEYCLOAK_CLIENT_ID}}
        client_secret: ${{KEYCLOAK_CLIENT_SECRET}}
        discovery: ${{KEYCLOAK_DISCOVERY_URL}}
        realm: ${{KEYCLOAK_REALM}}
        scope: "openid profile"
        bearer_only: false
        introspection_endpoint_auth_method: "client_secret_post"
        ssl_verify: false
        session:
          secret: ${{APISIX_SESSION_SECRET_KEY}}
        logout_path: "/logout"
        post_logout_redirect_uri: ${{UE_LOGOUT_URL}}
        set_userinfo_header: true
        unauth_action: "pass"
    uri: "/ws"
    enable_websocket: true

#END
